jquery-validation/jquery-validation

src/additional/postalCodeCA.js
test/methods.js

Allow both upper case and lower case characters and zero or more spaces between the Forward Sorting Area and Local Delivery Unit portions as users do not always use all upper case or include a space (see https://github.com/wet-boew/wet-boew/issues/6760).
Correct the regular expression to fail entries that include invalid characters D, F, I, O, Q, and U which are not used in Canadian postal codes (emphasis mine):
<blockquote>
<p>The postal codeOM is a six-character code defined and maintained by Canada Post Corporation (CPC) for the purpose of sorting and delivering mail. The characters are arranged in the form 'ANA NAN', where 'A' represents an alphabetic character and 'N' represents a numeric character (e.g., K1A 0T6). The postal codeOM uses 18 alphabetic characters and 10 numeric …

Additionals: Updates to postalCodeCA method

---

src/core.js
test/methods.js

Fix for #1567 ; Instead of just using validating field's value to determine whether or not to skip the remote check, use the data of the request that would go to the endpoint, as this may affect the validation result.

#1567 Instead of using validating field's value to skip api call, use the serialized data object of the request

---

src/core.js

This reverts commit b2df81ccb6276a6a39661ebd1ddd4a54c182217e.

Revert "Core: escape errorID only for use in the regex"

---

src/localization/messages_pt_BR.js

Changed a word to a more commonly used one.
Also, corrected the key 'cifES'. It was misspelled as 'cifEE'.

Improving pt_BR translation and fixing a typo on the 'cifES' key.

---

src/core.js
test/error-placement.js
test/index.html

As suggested by Jörn in [#1523 (comment)](https://github.com/jzaefferer/jquery-validation/issues/1523#issuecomment-122916989):
>Could you look into writing a unit test that captures what you have in your jsfiddle? Once that works, the suggested fix is much easier to verify and the test will prevent further regressions.
This pull request is a continuation of #1587 (so you can close it in favor of this) :
>The error ID was being escaped for use in a regex, but these escaped characters were also being passed on to the aria-describedby value set in the HTML, which means the ID doesn't match up with the ID of the element it's referring to.
**Note:**
The first commit contains the unit test, while the second one contains the fix.

Fixed #1523

---

src/core.js
test/.jshintrc
test/index.html
test/rules.js

The user can change/transform the value of an element before validating
the element in question. The `normalizer value` will be then used by
the associated methods instead of the `real one`.
Ref: #1602

Core: Added transformation/normalization layer

---

src/core.js
test/methods.js

This pull request adds a "pending" class to the input element while there is remote validation pending. This allows you, for example, to add a loading animation to visually indicate that there outstanding activity for the field.
This is updated version of a previous pull request:
https://github.com/jzaefferer/jquery-validation/pull/1221

Pending class2

---

src/core.js
test/index.html
test/test.js

Currently the validation library only works on classic form elements. However, there is no reason it can't work on rich text elements that have names and use contentEditable. This change adds support for these tags.

Add support for contentEditable tags

---

src/core.js
test/test.js

For historical reasons, the value IDL attribute prefixes the file name
with the string "C:\fakepath\". As a result of this, this fix will extract
the file name from the value IDL attribute in a backwards-compatible way.
For more details, see:
- http://www.w3.org/TR/html5/forms.html#dom-input-value-filename
- http://www.w3.org/TR/html5/forms.html#fakepath-srsly
Fixes #1615

Core: Extract the file name without including "C:\fakepath\"

---

src/core.js
test/messages.js

The `this` inside `$.each()` refers to the current value of the
`Objcet|Array` we iterate over, not the plugin instance.
Ref https://github.com/jzaefferer/jquery-validation/pull/1614#discussion_r51156526

Core: Fix TypeError in `showLabel` when using `groups` settings

---

src/core.js
test/rules.js

Tests: Calling .rules() on an empty jQuery object results in an error.

---

src/core.js
test/test.js

bind the event just once, avoiding the unbind-rebind overhead.
Also, unbind it when destroying the plugin.
Ref #1704
Ref #1707

Core: Bind the `blur` event just once in `equalTo` rule

---

src/core.js
test/index.html
test/test.js

Resolves #1891 
I'm adding the easiest solution from list described in issue.
Here example with build based on my changes - https://jsfiddle.net/5vumyq0k/

Init: add binding for input with button type

---

src/core.js
test/rules.js

This PR added support for using a global normalizer for all elements of the form, which will run for all elements if it's present in the top level (the same level as `rules`) without affecting the current behaviour, that way you can transform the values of a set of elements without attaching the same normalizer to the aforementioned elements, and you can override it on element level by specifying a normalizer for the specific element that you want to transform differently.
In pseudo code, this will look like:
``` js
$("#myForm").validate({
normalizer: function(value) {
// Trim the value of every element
return $.trim(value);
},
rules: {
username: {
required: true,
// Here, we override the global normalizer
normalizer: function(value) {
value = value.replace("something", "new thing"); …
```

Core: Add support for defining a global normalizer

---

src/additional/nifES.js
test/methods.js

Fixed bug in validation of Spanish nif for specific case of temporary foreign NIFs.
Added test for specific case.
Closes #1913
Thank you!

Additional: Fixed validation for specific case for Spanish NIFs.

---

src/core.js
test/index.html
test/test.js

JSFiddle -
https://jsfiddle.net/0b3we0gm/9/ (with the fix)
https://jsfiddle.net/0c8nvnob/7/ (without the fix)
Non-Firefox browsers dispatch `click` on descendants of `<button>`, which breaks
the submitHandler logic that adds a hidden field with the name and value of the
submit button (since it is not included in the submission if it did not
initiate the submission, which might be the case when using `form.submit` in
`submitHandler` and returning `false`). `submitButton` is instead a descendant of
`<button>` and the hidden field does not compensate for the lack of an actual
submit button.
This would fix https://crbug.com/668524 and make `submitButton` an actual button.
The issue is reproducible in Chrome.
Firefox does not dispatch events to the descendants of `<button>` (but the …

Added support for button elements with descendants

---

src/additional/nipPL.js
src/localization/messages_pl.js
test/methods.js

This PR adding new custom method to validate Polish tax identifier number (NIP).
Working example:
https://jsfiddle.net/dycqm91k/1/

Polish tax id validation method

---

src/core.js
test/index.html
test/test.js

Core: assign rules to contenteditable via `.validate()` and `.rules()`

---

src/localization/methods_nl.js

The Dutch number format is the same as the German number format. See https://en.wikipedia.org/wiki/Decimal_mark#Countries_using_Arabic_numerals_with_decimal_comma
Closes #2013

methods_nl.js: update number validation

---

test/test.js

This test was added a year+ ago as part of #1679, but forgot to assign a description to it. Discovered it today while browsing the test files.

Test: Add missing description to a test

---

src/localization/messages_fr.js
src/localization/messages_tr.js

I searched all localization files for "{0}" to see if I could find any without a call to the `format `method.  Found two.
Partially fixes #2065 (the French part, identified by @HawkonDK).  Danish translations were added in https://github.com/jquery-validation/jquery-validation/pull/2067, so that issue can be closed with this PR.

Localization: Add missing format method.

---

src/additional/maxfiles.js
src/additional/maxsize.js
src/additional/maxsizetotal.js
test/methods.js

This is a continuation of abandoned PR https://github.com/jquery-validation/jquery-validation/pull/1512, in that it validates the maximum size of a selected file.
Since the "file" type can contain the multiple attribute, another method was added to validate the maximum size of all selected files.  Finally, a third method was added to validate the maximum number of files.

Additional: max size and number of files

---

src/localization/messages_bg.js

The "maxlength" message has wrong meaning in Bulgarian. The current meaning is:
Please enter more than {0} characters.
The correct meaning should be:
Please enter no more than {0} characters.
I could use "less" (по-малко) to mean the same thing, but it does not sound natural in this context.

Translation: fix meaning in Bulgarian sentence

---

.travis.yml

This fixes the flast failed builds

Build: test on node 6.x and drop node 0.12.x

---

src/additional/phoneUS.js
test/methods.js

Adds support to the phoneUS validator for a 1 in the third position of the CO code to support non-geographical US area codes. 
For example:
800-811-xxxx (replacing xxxx with some real 4 digit number) is a valid US phone number but not currently accepted by the validator.

Additional: allow N11 exchange for non-geo US phone. Fixes #1695

---

Gruntfile.js
build/release.js
package.json

With this, running `grunt release` will generate ~~3 new files~~ 1 file in the `dist` folder:
* ~~`sri-core.json`: contains the hashes of `jquery-validate.js` and `jquery-validate.min.js`~~
* ~~`sri-additional.json`: contains the hashes of `additional-methods.js` and `additional-methods.min.js`~~
* ~~`sri-localization.json`: contains the hashes of all JS files inside `localization` folder~~
* `jquery-validation-sri.json`: contains the hashes of all JS files inside `dist` folder
I can add those files to the list of [distribution files][1] in case we want to commit them to GitHub.
[1]: https://github.com/jquery-validation/jquery-validation/blob/b70fcc20f1bcdcd63422686595a48950326309f1/build/release.js#L40-L46
//c @staabm @vanillajonathan

Build: Generate sub-resource integrity hashes of the distribution files

---

.github/stale.yml

I will install the bots on this repo after we agree on the message of the comments.
Ref #2127
/cc @staabm

Add support for Stale bot

---

.github/stale.yml

Hi @staabm,
This will help us more to not miss some important issues. 30 days is good, but sometimes I want to address an issue and a month pass quickly.
Also, do you think we need to add some labels (e.g `question`) to the list of excluded labels?

All: Increase number of days of inactivity of stale issues to 60 days

---

src/core.js
test/methods.js
test/test.js

Core: Don't call submitHandler when in debug mode

---

src/core.js

This PR changes the focus() to trigger("focus"), so that it is not flagged up in non-live environments using the jQuery Migrate 3.x plugin.
https://github.com/jquery-validation/jquery-validation/issues/2238

Core: change focus() to trigger("focus")

---

src/core.js

This fixes the issue with deprecation and adds the polyfill for `String.prototype.trim` for browser support.

Core: Fixes deprecated calls to jQuery trim. Fixes #2327

---

README.md

Adding Accessibility section to the readme that speaks to using `errorElement` in the `validate()` method.
Thank you!

Add Accessibility section to Readme

---

test/test.js

There is a small typo in test/test.js.
Should read `attached` rather than `atteched`.

docs: Fix simple typo, atteched -> attached

---

src/core.js
test/test.js

https://jsfiddle.net/bytestream/a16ehn0L/18/
When jquery-validation is used with a WYSIWYG editor there can be a delay in synchronisation between the `div[contenteditable]` and the underlaying `textarea`. This delay combined with remote validation leads to a state where the form is valid but does not submit.
The issue is hopefully fairly obvious when looking at `stopRequest`:
```
if ( valid && this.pendingRequest === 0 && this.formSubmitted && this.form() ) {
```
`this.form()` can cause new remote validation rules to fire. In the vast majority of cases, the input data is the same and so jquery-validation looks at the cached result and doesn't bother with another AJAX request. In this case however, the delay in synchronisation causes the request data to change so jquery-validation fires …

Core: wait for pendingRequests to finish before submitting form

---

src/core.js

Fixes `jQuery.fn.submit() event shorthand is deprecated`
https://github.com/jquery/jquery-migrate/blob/main/warnings.md#shorthand-deprecated-v3-jqmigrate-jqueryfnclick-event-shorthand-is-deprecated

Core: fix deprecated jquery .submit() event shorthand

---

src/ajax.js
src/core.js
test/methods.js

Fixes #2434
- Add a new jQuery global method `$.ajaxAbort( port )` to the jQuery Ajax extension that is provided by this library. This method allows to abort an ajax request without sending a new one.
- Call this method at the beginning of `check()` method.

Core: fix race condition in remote validation rules

---

src/core.js
test/methods.js

Ref #2434
Ref #2435
Follow up on #2435. Removal of the pending class from element was missing.

Core: remove pending class from fields with an aborted request

---

src/localization/messages_pt_BR.js

"É requerido" although correct is weird in this context (it's much more used in formal settings for documents known as requerimentos) and too much of a literal translation. This change aims to improve user-friendliness in this particular message.
**Popularity of one vs the other:**
**Demonstration of how the adjective requerido is much more widely used in judicial settings:**
(Jus brasil is one of the go-to websites as a judicial source and "cpc"/"codigo civil" both refer to brazil's civil laws)
Thank you!

Localization: small improvement to pt_BR

---

demo/ajaxSubmit-integration-demo.html

This fixes attribute assignment it was `minlength "5"` but it needs the `=` equal sign.

Demo: fix minlength validation in ajaxSubmit-integration-demo.html

---

src/core.js
test/error-placement.js
test/index.html

This adds a new constructor option "escapeHtml".
There is a script injection risk if the messages set via $.validator.messages etc. are originating from a user localizable dictionary, like a translation screen as the showLabel function uses .html() to set the label content. Even in cases where that is not an issue, if the message itself contains a format placeholder like "{0} is not valid value for this field", as the value passed to {0} is a user input, it still provides an opportunity for script injection attacks albeit at a lower risk.

Core: Added escapeHtml option to avoid XSS attacks via showLabel method

---

src/localization/messages_fr.js

This adds a French translation message for the [currency validation method](https://github.com/jquery-validation/jquery-validation/blob/master/src/additional/currency.js).
Just for reference, the English version of this message is:
> Please specify a valid currency.

Localization: Add French currency translation

---

src/core.js
test/methods.js
test/test.js

Fixes #2479
There is a bug in remote validation: if the Ajax request for a remote validation rule fails, an incorrect result will be stored in `$element.data('previousValue')`. Then, if the same input is validated again, the previous incorrect result will be re-used and no Ajax request will be sent.
In particular, this bug will occur when a request is aborted. Which happens more often (as it should) since #2435 was merged. (although the bug could already occur before #2435 in case of a server error).
I also had to fix the `"remote, data previous querystring"` test. It turns out the mocked request for this test was wrong. Which didn't matter before this PR: the failed remote validation was incorrectly considered as a validation result.

Core: fix remote validation when input is the same as in aborted request
