test/methods.js

Core: method.js fix tests for #1567

---

src/core.js
test/test.js

See #1508 for more information.
This pull request removes also the need for `lastElement`

Fixes #1508: Validation fails to trigger when next field is already filled out

---

src/core.js
test/error-placement.js
test/index.html
test/test.js

Fixed #1603

---

src/additional/creditcard.js
src/core.js
test/additional/creditcard.js
test/index.html
test/methods.js

As mentioned by Jörn in [#1506 (comment)](https://github.com/jzaefferer/jquery-validation/issues/1506#issuecomment-116327217)

Core: Split out `creditcard` method

---

Gruntfile.js

See https://github.com/jzaefferer/jquery-validation/pull/1597

Build: Adds CommonJS-support in build process. Enhances PR #1597

---

src/core.js
test/rules.js
test/test.js

This change fix the bug when used with remote rule, it's already fixed
whith other rules in commit 737630e7888485882c8c65b0f8ac5328950be0ac
Ref #1508

[Remote rule] Core: Validation fails to trigger when next field is already filled out

---

src/localization/messages_ur.js

Adding Urdu localisation messages.
Thank you!

add Urdu locale

---

src/localization/messages_nl.js

Before submitting a pull request, please make sure to follow these rules:
* Your code should contain tests relevant for the problem you are solving.
* Your commits messages format should follow the jQuery git commit message format (http://contribute.jquery.org/commits-and-pull-requests/#commit-guidelines).
* The pull request should reference existing issues or link to a reproducible demo.
* Please review the guidelines for contributing (CONTRIBUTING.md) to this repository for more information.
Please describe your pull request.
Thank you!

Added translation for step property, this was not translated.

---

src/localization/messages_no.js

Added the translation for the step valdation, based on Norsk Bokmål

Added step translation

---

src/localization/messages_sd.js

Adding Sindhi localisation messages.
Thank you!

add Sindhi locale

---

test/test.js

Tests: removed duplicated test

---

README.md

README: removed gitter badge

---

src/core.js
test/test.js

Core: count invalid fields with empty message in `numberOfInvalids()`

---

src/localization/messages_ja.js

Added Step Range Validation  to messages_ja

---

src/additional/netmask.js
test/additional/netmask.js
test/index.html

Add a method to validate netmask.
Close-pull-request: #1831 #Add test cases
Signed-off-by: Wang Sen <wangsen@linux.vnet.ibm.com>

Additional: add netmask validation method

---

src/additional/cifES.js
src/additional/nieES.js
src/additional/nifES.js

The cifES, nifES and nieES not check if field is optional, and if field is empty show a error message.

Additional: add optional support to cifES, nifES and nieES

---

package.json
test/test.js

Upgrade `QUnit` to 2.3.3 and stop using deprecated API

---

src/core.js
test/test.js

Fixed fiddle: https://jsfiddle.net/Arkni/sofq4qbw/9/

stopRequest() doesn't pass on the submit button value (based on #1596)

---

README.md

Ref https://github.com/jquery-validation/jquery-validation/issues/2027#issuecomment-313874350

Readme: Add note about trimming whitespaces inside required method

---

src/localization/messages_fr.js

This localization seems to be missing in every language.

Localization: Add French translation for notEqualTo method.

---

src/core.js
test/rules.js

Needs #2053 to be merged before in order for tests to pass

Core: Allow the normalizer to return any value

---

src/core.js
test/rules.js

Core: guard against null & undefined values in required method

---

src/localization/messages_sv.js

Add validation message for remote

---

src/additional/greaterThan.js
src/additional/greaterThanEqual.js
src/additional/lessThan.js
src/additional/lessThanEqual.js
src/core.js
test/index.html
test/methods.js
test/test.js

Fixes #2030.
Tests are limited to integers, but I think that other data types would work too.

Core: Add greaterThan and lessThan methods.

---

README.md

Added Shield.io release badget and a tab error in one of the code examples

Shield.io release badget

---

src/additional/creditcardtypes.js
test/methods.js

For the sake of closing an issue, this fixes #1904 in the manner suggested by @tritontech, with updated tests.

Additional: Add new BIN range for MasterCard.

---

CONTRIBUTING.md

Hello, @Arkni, 
Translator has reported possible source content issue.  It seems that the string is duplicated by mistake. 
Please, help to check my proposed file change into the article and help to merge if you agree with fix. If not, please, let me know either if you would like me to fix it in another way within this PR, if you prefer to fix it in another PR, or if I should close this PR as by-design. In case of using another PR, please, let me know of your PR number, so we can confirm and close this PR.
Many thanks in advance.
Before submitting a pull request, please make sure to follow these rules:
* Your code should contain tests relevant for the problem you are solving.
* Your commits messages format should follow the jQuery git commit message format …

M16514: Possible incorrect addition of "To install"

---

src/additional/creditcard.js

Updated the link to the docs of EAN

Updated link to EAN docs

---

src/additional/phonePL.js
src/localization/messages_pl.js
test/methods.js

Add method to validate Polish telephone numbers.

phonePL validation method

---

src/localization/messages_pt_BR.js

Typo pt-BR

---

src/localization/messages_zh.js

Added Step Validation message for zh

localization: add step validation string to message_zh

---

src/core.js
test/index.html
test/rules.js

Cast empty data attributes to 'true'

---

demo/bootstrap/index-bs4.html

Ref #2131.
Simple page showing how to use jquery-validation with Bootstrap 4.

Demo: Add sample code for Bootstrap 4 usage

---

src/core.js

Fixes not supported method hasAttribute on IE with enabled compatibility mode
Fixes #2141

Core: Use of jQuery attr instead of hasAttribute. (#2141)

---

src/localization/methods_it.js

Methods: Localized methods for italian culture (it)

---

src/additional/nisBR.js
src/localization/messages_pt_BR.js
test/methods.js

I've changed some reviews like orientation by @Arkni.
I've removed some spaces then I've chanced creation of date the new method nisBr.
Thank you!

Nis br method review

---

src/additional/creditcardtypes.js

Fix a typo: "the the" -> "the"
Thank you!

Fix a typo: "the the" -> "the"

---

src/localization/messages_sv.js

Add Swedish translation for pattern.
Thank you!

Add Swedish translation for pattern.

---

src/additional/cnpjBR.js
src/localization/messages_pt_BR.js
test/methods.js

Created rule for validation of the registration code of Brazilian companies.

Additional: Included validation rule for CNPJ from Brazil

---

src/additional/mobileRU.js
test/methods.js

mobile number for Russia Federation

---

src/additional/cnpjBR.js
src/additional/cpfBR.js

Additional: CNPJBR and CPFBR
Fix not to fail when field is not required

Additional (CNPJBR and CPFBR): Fix not to fail when field is not required

---

src/core.js

Fixes #2211
Fixes #2214
Fixes #2217
Fixes #2225
Fixes #2233

Core: Fix contenteditable detection's regression introduced in #2142

---

src/localization/messages_zh_TW.js

Add `zh_TW` translation for step validation

add step validation localization in message_zh_TW

---

src/core.js

Replaces functions deprecated in jQuery 3 as per https://api.jquery.com/category/deprecated/

Replaced deprecated jQuery functions

---

src/core.js

Build is failing as a result of https://github.com/jquery-validation/jquery-validation/pull/2154
```
Running "jscs:all" (jscs) task
If statement without curly braces at src/core.js :
1033 |  // as a literal part of a name/id or any selector.
1034 |  escapeCssMeta: function( string ) {
1035 |   if (string === undefined) return "";
-----------^
1036 |   return string.replace( /([\\!"#$%&'()*+,./:;<=>?@\[\]^`{|}~])/g, "\\$1" );
1037 |  },
Missing space after opening round bracket at src/core.js :
1033 |  // as a literal part of a name/id or any selector.
1034 |  escapeCssMeta: function( string ) {
1035 |   if (string === undefined) return "";
---------------^
1036 |   return string.replace( /([\\!"#$%&'()*+,./:;<=>?@\[\]^`{|}~])/g, "\\$1" );
1037 |  },
Missing space before closing round …
```

Core: fix code style

---

README.md

Replace travis build status badge with github workflow badge.
Thank you!

README: update build status badge

---

Gruntfile.js

Fix #2385
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>

Gruntfile.js: add LICENSE.md to zip tarball

---

src/core.js
test/methods.js

Core: Allow negative decimal with no 0
